apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: llm-agent
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/llm-agent
          ports:
            - containerPort: 8080
